## 单位是毫秒
cut_line: 600  # 如果一个句子中，有两个字的间隔超过1000毫秒，以此把句子切成两句，防止长句过长
combine_line: 400 # 如果两个字的间隔小于400毫秒，就把它们合并到一句，可以增加连贯性，同时合并一些语气词。
ignore_line: 2500 # 如果句子长度短语2.5s，就把它丢弃。
## 对于不同的任务我们不一定需要全部用上。
base_model: "./models/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch"  # base
vad_model: "./models/speech_fsmn_vad_zh-cn-16k-common-pytorch" #支持长音频，自动分隔
punc_model: "./models/punc_ct-transformer_zh-cn-common-vocab272727-pytorch"  # 检测语音活动，给出标点。