[project]
name = "ADL"
version = "0.0.5"
description = ""
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "funasr==1.2.6",
    "modelscope>=1.23.1",
    "numpy==1.26.4",
    "torch==2.2.0",
    "torchaudio==2.2.0",
    "tomli_w==1.2.0",
    "pydantic>=2.10.6",
    "setuptools==76.0.0",
    "streamlit==1.43.2",
    "streamlit-antd-components==0.3.2",
    "pandas==2.2.3",
    "pydub>=0.25.1",
]
authors = [{ name = "MrXnneHang", email = "XnneHang@gmail.com" }]
keywords = []
license = { text = "MIT" }


[project.scripts]
label = "label.__main__:main"

[dependency-groups]
dev = [
  "pyright>=1.1.391",
  "ruff>=0.9.3",
  "pytest>=8.3.4",
  "pytest-rerunfailures>=15.0",
]


[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu118", marker = "sys_platform == 'win32'" }, # sys_platform : 'win32' , 'linux' , 'Darwin'
  { index = "pytorch-cpu", marker = "sys_platform != 'win32'"}
]
torchaudio = [
  { index = "pytorch-cu118", marker = "sys_platform == 'win32'" },
  { index = "pytorch-cpu", marker = "sys_platform != 'win32'"}
]

[tool.hatch.build.targets.wheel]
packages = ["src/label"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# 选取的该版本 Pytorch 仅仅支持 310 311.
# < 3.11 需要额外安装 tomlilib 
# < 3.11 不支持 *tuple 的解包。(_dataclass.py 中涉及)
# 于是，该项目只能在 3.11 运行，3.12 及以上需要考虑手动升级 pytorch。