batch_size_s = 300
device = "cuda"
punctuation_list = "，。；、？！,.;?!"
custom_output_dir = false
raw_audio_dir = "./raw_audio"
cache_dir = "./cache"
output_dir = "./output"
hot_words_path = "./hot_words.txt"
FFMPEG_PATH = "ffmpeg"
base_model = "./models/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch"
vad_model = "./models/speech_fsmn_vad_zh-cn-16k-common-pytorch"
punc_model = "./models/punc_ct-transformer_zh-cn-common-vocab272727-pytorch"
cut = false
cut_line = 400
combine = false
combine_line = 400
max_sentence_length = 20
